name: 🐛 Bug Report
description: Report a bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure there aren't already any open/closed issues for this problem.

  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Reproduction
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. do this
        2. do that
        3. etc
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other context about the problem here. (logs, screenshots, videos, etc)